/*
 * BATester.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using Merged.Standard.Batester.Controllers;

namespace Merged.Standard.Batester
{
    public sealed class BATesterClient
    {
        /// <summary>
        /// Configuration instance
        /// </summary>
        private Configuration Config { get; }

        private readonly object syncObject = new Object();
        private APIController client;

        /// <summary>
        /// Provides access to APIController controller
        /// </summary>
        public APIController Client
        {
            get
            {
                if (client == null)
                {
                    lock (syncObject)
                    {
                        if (client == null)
                        {
                            client = new APIController(Config);
                        }
                    }
                }
                return client;
            }
        }

        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        internal BATesterClient(Configuration config)
        {
            this.Config = config;
        }
        #endregion
    }
}