/*
 * CustomHeaderSignature.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using CustomHeaderSignature.Standard.CustomHeader;
using Merged.Standard.Batester;

namespace Merged.Standard
{
    public sealed class MergedClient
    {
        /// <summary>
        /// Configuration instance
        /// </summary>
        public Configuration Config { get; }

        private readonly object syncObject = new Object();
        private BATesterClient bATesterClient;

        private CustomHeaderClient customHeaderClient;


        public BATesterClient BATester
        {
            get
            {
                if (bATesterClient == null)
                {
                    lock (syncObject)
                    {
                        if (bATesterClient == null)
                        {
                            bATesterClient = new BATesterClient(Config);
                        }
                    }
                }
                return bATesterClient;
            }
        }

        /// <summary>
        /// Provides access to CustomHeaderSignatureController controller
        /// </summary>
        public CustomHeaderClient CustomHeader
        {
            get
            {
                if (customHeaderClient == null)
                {
                    lock (syncObject)
                    {
                        if (customHeaderClient == null)
                        {
                            customHeaderClient = new CustomHeaderClient(Config);
                        }
                    }
                }
                return customHeaderClient;
            }
        }

        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public MergedClient()
        {
            this.Config = new Configuration();
        }

        /// <summary>
        /// Default constructor
        /// </summary>
        public MergedClient(Configuration config)
        {
            this.Config = config;
        }
        #endregion
    }
}