/*
 * CustomHeaderSignature.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using CustomHeaderSignature.Standard.Controllers;
using CustomHeaderSignature.Standard.Http.Client;
using CustomHeaderSignature.Standard.Utilities;

namespace CustomHeaderSignature.Standard
{
    public sealed class CustomHeaderSignatureClient
    {
        /// <summary>
        /// Configuration instance
        /// </summary>
        public Configuration Config { get; }

        private readonly object syncObject = new Object();
        private CustomHeaderSignatureController customHeaderSignature;

        /// <summary>
        /// Provides access to CustomHeaderSignatureController controller
        /// </summary>
        public CustomHeaderSignatureController CustomHeaderSignature
        {
            get
            {
                if (customHeaderSignature == null)
                {
                    lock (syncObject)
                    {
                        if (customHeaderSignature == null)
                        {
                            customHeaderSignature = new CustomHeaderSignatureController(Config);
                        }
                    }
                }
                return customHeaderSignature;
            }
        }

        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public CustomHeaderSignatureClient()
        {
            this.Config = new Configuration();
        }

        /// <summary>
        /// Default constructor
        /// </summary>
        public CustomHeaderSignatureClient(Configuration config)
        {
            this.Config = config;
        }
        #endregion
    }
}